server:
  port: 56085
  servlet:
    context-path: /sailing

spring:
  application:
    name: sailing

  main:
    allow-bean-definition-overriding: true



  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    host: localhost
    port: 6379
    shutdown-timeout: 100
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: 10000
    timeout: 10000
    #password: 123456

sms:
  qcloud:
    appId: 0
    appKey: appKey
    templateId: 0
    sign: 签名

swagger:
  enable: true

logging:
  config: classpath:log4j2.xml
    


